title: Sneha Aenugu
name: Sneha Aenugu
description: Computational neuroscience, reinforcement learning, and human decision-making.
url: "https://snehaaenugu.com"
author:
  name: Sneha Aenugu
  email: saenugu@salk.edu
markdown: kramdown
highlighter: rouge
javascript_enabled: true
defaults:
  - scope:
      type: posts
    values:
      layout: post
      permalink: /post/:title
plugins:
  - jekyll-sitemap
exclude:
  - README.md
  - vendor
